### ISSUE TITLE
Trabalho Final da Disciplina - 1ª Entrega

### ISSUE THREAD

**Issue by altjohndev** [fga-verival/2017-1Grupo1#7]
- [x] **A**: Tema do estudo
- [x] **B**: Problema a ser resolvido
- [x] **C**: Proposta de solução: Objetivo Geral
- [x] **D**: Proposta de solução: Objetivos Específicos
- [x] **E**: Plano de elaboração do trabalho
- [x] **F**: Definição das aplicações previstas para validar a proposta de solução
